export const SET_ADDITIONAL_STOCK_DATA_SET1 = 'SET_ADDITIONAL_STOCK_DATA_SET1';
export const SET_ADDITIONAL_STOCK_DATA_SET2 = 'SET_ADDITIONAL_STOCK_DATA_SET2';
export const SET_ADDITIONAL_STOCK_DATA_SET3 = 'SET_ADDITIONAL_STOCK_DATA_SET3';
