export const SET_OPTIONS_CAHIN_PRICE = 'SET_OPTIONS_CAHIN_PRICE';
export const SET_EXPIRATION_DATE = 'SET_EXPIRATION_DATE';
export const SET_MARKET_PRICE_OF_SYMBOL = 'SET_MARKET_PRICE_OF_SYMBOL';
export const SET_ACTIVE_EXPIRY_DATE = 'SET_ACTIVE_EXPIRY_DATE';
